<b>Use PyTorch to build a simple neural network.</b>

In [1]:
# Import PyTorch
import torch

In [2]:
# Activation function
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [4]:
## Calculate the output of this network using the weights and bias tensors
h = torch.sum(features * weights) + bias
y = activation(h)
y

tensor([[0.1595]])

In [5]:
## Calculate the output of this network using matrix multiplication
h = torch.mm(features, weights.view(5,1)) + bias
y = activation(h)
y

tensor([[0.1595]])

<b>Use PyTorch to build a simple neural network multilayer.</b>

In [6]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

<b>Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`.</b> 

In [7]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])
